### ISSUE TITLE
TOO FAST warning on 503 is triggered often

### ISSUE THREAD

**Issue by securitybites** [hehnope/slurp#1]
I was able to use the tool for about 50 requests then it started kicking back "TOO FAST" on the 503's. Is there a way to slow down the requests per second so its throttled?

**Comment by hehnope** [comment]
If I recall that is because your concurrency is too high. You should be able to lower it to avoid that error.

**Comment by jaikishantulswani** [comment]
@hehnope I am also getting the same, meanwhile I havn't found any switch for decreasing the concurrency.

**Comment by hehnope** [comment]
If you guys look here https://github.com/hehnope/slurp/blob/master/scanner/external/external.go#L313-L317 it re-adds the domain to the queue for processing later. The question would be that when this occurs does it ever finish? If not, then slowing it down would be a good option.

**Comment by cjdupreez** [comment]
To decrease the concurrency, use the -c flag:

./slurp domain -t example.com -c 1

**Comment by hehnope** [comment]
Closing because concurrency control handles this. The application also puts any 503 errors received back in the queue for processing later. This should not be an issue.

**Comment by B1gD4ddy** [comment]
No matter what -c flag I set, its always same. I try with -c 1 also, but still same issue.

**Comment by hehnope** [comment]
Can you paste output? Did you try changing after you already got the error? How many cores does your system have when running?

**Comment by B1gD4ddy** [comment]
Yes, I try after got an error, restart PC and before error in output TOO FAST ...
Processor is i5 7th gen, 4 cores, ParrotOS.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hehnope** [comment]
@B1gD4ddy can you post information? Also, remember, the `503` is out of my control; if amazon starts throttling your IP then you're at their mercy. I just tested with `-c 10` and have no issues. But, when you have an issue I need to know your concurrency and some of the output log at minimum.

**Comment by hehnope** [comment]
Curious what you guys think a solution to this might be? I was thinking about lowering the concurrency of the channel on 503 detection and then sleeping for a bit, and if another 503 occurs doing the same thing. It seems that the 503 errors may be independent of concurrency, so I think hard-coding may be a bad idea? Obviously, `1` will be the min, but I think maybe `2` or `4` are reasonable? Curious what you guys think.

**Comment by hehnope** [comment]
I was implementing a way around this and I noticed that s3 now does throttling and soft bans per IP potentially _instead of_ the `503` now. I was not able to reproduce the `503` at all (using up to 10,000 concurrency), but a public bucket that I do know is "open" started returning 404 errors (`The specified bucket does not exist`) for me. Returning the `404` when you potentially have reached the original `503` and, there are no identifying headers that make it obviously a "lie" means it makes it very hard to now detect if you've been throttled or not.

**Comment by fatalsecurity** [comment]
Could you set up a periodic check to a S3 bucket that you yourself own, that you know is publicly accessible, and if it returns a 404 then you can determine if you've been throttled?

**Comment by hehnope** [comment]
That is possible, but do I want to maintain a bucket? no haha. However, another option might be if someone is providing an API service to a bucket, then that may work. So, something like

slurp -> http service > (service responds with `true`/`false` indicating if open or not

**Comment by hehnope** [comment]
Amazon may have interpreted the 10,000 concurrency as a DDoS and it was just blocked at the firewall. However, 2048 concurrency does not reproduce `503` at all. So... potential solution may not be valid. Anything higher than 2048 causes read errors on my laptop (which is an i7).
