### ISSUE TITLE
Cannot import module github.com/sirupsen/logrus

### ISSUE THREAD

**Issue by abdulfasithnpm** [hehnope/slurp#10]
Not able to build saying "go: github.com/Sirupsen/logrus@v1.4.0: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"

**Comment by hehnope** [comment]
I've seen that happen if the `S` part of Sirupsen is capitalized. It's not supposed to be. I just checked through the repo and did not find any capital `S` variants. Also nuked the go build cache incase. Are you use an old version?

**Comment by abdulfasithnpm** [comment]
Thank you!! my version is a problem now fixed.
