### ISSUE TITLE
internal mode not working

### ISSUE THREAD

**Issue by Phoenix1112** [hehnope/slurp#2]
Hello there . Firstly thank you for this project. There are some things I don't understand. I haven't seen any information about how to use the internal command exactly.

I work like this

./main internal

output : INFO[0000] Determining public buckets....  
------------------------------------------------------------------
OR

./main internal -r us-west-2

output : INFO[0000] Determining public buckets....

-------------------------------------------------------------------------------
I also do normal scans and I see this output many times.

INFO[0021] TOO FAST (added to queue to process later) 
INFO[0021] TOO FAST (added to queue to process later) 

--------------------------------------------------------------------------------
./main domain -p permutations.json -t fanduel.com -c 1
I used the -c command for this, but it still didn't work..

The interesting part is that I do not get such errors on my vps server. but when I run the program on my home computer, I always get the same error.(TOO FAST (added to queue to process later)

How do we scan the domain with the internal command? please answer.

**Comment by hehnope** [comment]
You do not scan domains with internal; internal simply functions as a way to scan all your S3 buckets based on your AWS credentials.
