### ISSUE TITLE
Export the permutations

### ISSUE THREAD

**Issue by xopodssec1** [hehnope/slurp#4]
It is possible to export the permutation list?

**Comment by hehnope** [comment]
@xopodssec1 do you mean create the permutations and then write them to stdout or a file?

**Comment by hehnope** [comment]
Added this feature in 24b273f1f2afac40d6f8411292ba41f14dbe1639, use `-g` to export for `domain` or `keyword` on the CLI.

**Comment by xopodssec1** [comment]
Just This! Thanks man.
